site_name: KazDATA Documentation
site_description: Official documentation for KazDATA platform
site_url: https://help.kazdata.kz

# Theme configuration
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - toc.follow
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/logo.svg
  logo: assets/logo.svg

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - toc:
      permalink: true
      title: On this page
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Plugins
plugins:
  - search:
      lang:
        - en
        - ru
  - tags
  - glightbox:
      auto_caption: true
      caption_position: bottom
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      reconfigure_material: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
          nav:
            - Home: index.md
            - Getting Started:
              - Platform Overview: getting-started/platform-overview.md
              - Quick Start: getting-started/quick-start.md
              - Registration: getting-started/registration.md
              - Subscription: getting-started/subscription.md
              - Interface: getting-started/interface.md
              - FAQ: getting-started/faq.md
            - Analysis:
              - Market Size: analysis/market-size.md
              - Competition: analysis/competition.md
              - Price: analysis/price.md
              - Regional: analysis/regional.md
              - Trends: analysis/trends.md
            - Use Cases:
              - Market Research: use-cases/market-research.md
              - Partner Search: use-cases/partners.md
              - Price Monitoring: use-cases/price-monitoring.md
              - Industry Analysis: use-cases/industry.md
            - Modules:
              - Import/Export:
                - Overview: modules/import-export/overview.md
                - Countries: modules/import-export/countries.md
                - Dynamics: modules/import-export/dynamics.md
                - Export: modules/import-export/export.md
                - Import: modules/import-export/import.md
                - Products: modules/import-export/products.md
              - Production:
                - Overview: modules/production/overview.md
                - Categories: modules/production/categories.md
                - Export: modules/production/export.md
                - Volume: modules/production/volume.md
              - Organizations:
                - Overview: modules/organizations/overview.md
                - Contacts: modules/organizations/contacts.md
                - Export: modules/organizations/export.md
                - Profiles: modules/organizations/profiles.md
                - Search: modules/organizations/search.md
              - Procurement:
                - Overview: modules/procurement/overview.md
                - Database: modules/procurement/database.md
                - Methods: modules/procurement/methods.md
                - Price: modules/procurement/price.md
                - Reports: modules/procurement/reports.md
                - Seasonal: modules/procurement/seasonal.md
            - Support:
              - Contact: support/contact.md
              - Troubleshooting: support/troubleshooting.md
              - Known Issues: support/issues.md
              - Updates: support/updates.md
        - locale: ru
          name: Русский
          build: true
          nav:
            - Главная: ru/index.md
            - Начало работы:
              - Обзор платформы: ru/platform-overview.md
              - Быстрый старт: ru/quick-start.md
              - Регистрация: ru/registration.md
              - Подписка: ru/subscription.md
              - Интерфейс: ru/interface.md
              - Вопросы и ответы: ru/getting-started/faq.md
            - Анализ:
              - Размер рынка: ru/analysis/market-size.md
              - Конкуренция: ru/analysis/competition.md
              - Цены: ru/analysis/price.md
              - Региональный: ru/analysis/regional.md
              - Тренды: ru/analysis/trends.md
            - Примеры использования:
              - Исследование рынка: ru/use-cases/market-research.md
              - Поиск партнеров: ru/use-cases/partners.md
              - Мониторинг цен: ru/use-cases/price-monitoring.md
              - Отраслевой анализ: ru/use-cases/industry.md
            - Модули:
              - Импорт/Экспорт:
                - Обзор: ru/modules/import-export/overview.md
                - Страны: ru/modules/import-export/countries.md
                - Динамика: ru/modules/import-export/dynamics.md
                - Экспорт: ru/modules/import-export/export.md
                - Импорт: ru/modules/import-export/import.md
                - Товары: ru/modules/import-export/products.md
              - Производство:
                - Обзор: ru/modules/production/overview.md
                - Категории: ru/modules/production/categories.md
                - Экспорт: ru/modules/production/export.md
                - Объем: ru/modules/production/volume.md
              - Организации:
                - Обзор: ru/modules/organizations/overview.md
                - Контакты: ru/modules/organizations/contacts.md
                - Экспорт: ru/modules/organizations/export.md
                - Профили: ru/modules/organizations/profiles.md
                - Поиск: ru/modules/organizations/search.md
              - Закупки:
                - Обзор: ru/modules/procurement/overview.md
                - База данных: ru/modules/procurement/database.md
                - Методы: ru/modules/procurement/methods.md
                - Цены: ru/modules/procurement/price.md
                - Отчеты: ru/modules/procurement/reports.md
                - Сезонность: ru/modules/procurement/seasonal.md
            - Поддержка:
              - Контакты: ru/support/contact.md
              - Устранение неполадок: ru/support/troubleshooting.md
              - Известные проблемы: ru/support/issues.md
              - Обновления: ru/support/updates.md

# Customization
extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: Русский
      link: /ru/
      lang: ru
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yourusername
  generator: false

# Copyright
copyright: Copyright &copy; 2024 KazDATA
